"""create image column for member table

Revision ID: 085a9806c5f3
Revises: 48c0df6fe64f
Create Date: 2026-04-08 16:17:29.588557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085a9806c5f3'
down_revision = '48c0df6fe64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
