"""add partner table

Revision ID: 340be4db3755
Revises: 5544eb30532a
Create Date: 2026-04-01 12:20:37.743385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340be4db3755'
down_revision = '5544eb30532a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logo'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partners')
    # ### end Alembic commands ###
