"""create product-pillar table

Revision ID: 7735d9ad1f48
Revises: 7c8b36e9d467
Create Date: 2026-02-24 08:57:40.146602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7735d9ad1f48'
down_revision = '7c8b36e9d467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_pillars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pillar_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], name=op.f('fk_product_pillars_pillar_id_pillars')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_pillars_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_pillars')
    # ### end Alembic commands ###
