"""create emails table

Revision ID: 7c8b36e9d467
Revises: 8c1de31d2e95
Create Date: 2026-02-21 11:39:23.242844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8b36e9d467'
down_revision = '8c1de31d2e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_subject', sa.String(), nullable=False),
    sa.Column('email_message', sa.String(), nullable=False),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    # ### end Alembic commands ###
