"""update partner model

Revision ID: 8bd3c69bbc91
Revises: 340be4db3755
Create Date: 2026-04-01 13:18:22.628807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd3c69bbc91'
down_revision = '340be4db3755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
