"""creare sustainable pillars table

Revision ID: 8c1de31d2e95
Revises: e776b6c270bd
Create Date: 2026-02-17 10:10:24.967068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1de31d2e95'
down_revision = 'e776b6c270bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sustainable_pillars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pillar_id', sa.Integer(), nullable=False),
    sa.Column('sustainable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], name=op.f('fk_sustainable_pillars_pillar_id_pillars')),
    sa.ForeignKeyConstraint(['sustainable_id'], ['sustainable_goals.id'], name=op.f('fk_sustainable_pillars_sustainable_id_sustainable_goals')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sustainable_pillars')
    # ### end Alembic commands ###
