"""update product model

Revision ID: ba836ea4b31a
Revises: 085a9806c5f3
Create Date: 2026-04-09 15:42:41.452243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba836ea4b31a'
down_revision = '085a9806c5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_img', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('base_img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('base_img')
        batch_op.drop_column('card_img')

    # ### end Alembic commands ###
