"""create multiple tables

Revision ID: f18ea5e472de
Revises: 
Create Date: 2026-04-10 22:10:17.552635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18ea5e472de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_subject', sa.String(), nullable=False),
    sa.Column('email_message', sa.String(), nullable=False),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('posted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pillars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('challenge', sa.String(), nullable=False),
    sa.Column('offering', sa.String(), nullable=False),
    sa.Column('success', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('state_of_world', sa.String(), server_default='', nullable=False),
    sa.Column('material', sa.String(), server_default='', nullable=False),
    sa.Column('progress', sa.String(), server_default='', nullable=False),
    sa.Column('card_img', sa.String(), nullable=True),
    sa.Column('base_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sustainable_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_members_team_id_teams')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_pictures_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_pillars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pillar_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], name=op.f('fk_product_pillars_pillar_id_pillars')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_pillars_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sustainable_pillars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pillar_id', sa.Integer(), nullable=False),
    sa.Column('sustainable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], name=op.f('fk_sustainable_pillars_pillar_id_pillars')),
    sa.ForeignKeyConstraint(['sustainable_id'], ['sustainable_goals.id'], name=op.f('fk_sustainable_pillars_sustainable_id_sustainable_goals')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sustainable_pillars')
    op.drop_table('product_pillars')
    op.drop_table('product_pictures')
    op.drop_table('members')
    op.drop_table('teams')
    op.drop_table('sustainable_goals')
    op.drop_table('products')
    op.drop_table('pillars')
    op.drop_table('partners')
    op.drop_table('news')
    op.drop_table('emails')
    op.drop_table('donations')
    # ### end Alembic commands ###
