"""update the attributes for the product model

Revision ID: ff07fe8c766d
Revises: 7735d9ad1f48
Create Date: 2026-02-24 12:08:01.910875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff07fe8c766d'
down_revision = '7735d9ad1f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_of_world', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('material', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('progress', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('progress')
        batch_op.drop_column('material')
        batch_op.drop_column('state_of_world')

    # ### end Alembic commands ###
